name: Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Get Commit Hash
        id: vars
        run: echo "HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Update Version
        run: |
          HASH=$(git rev-parse --short HEAD)
          CURRENT_VERSION=$(jq -r '.version' package.json)
          BASE_VERSION=$(echo $CURRENT_VERSION | awk -F'-' '{print $1}')
          NEW_VERSION=$(npm version --no-git-tag-version $BASE_VERSION | sed 's/v//')-dev.$HASH
          jq ".version=\"$NEW_VERSION\"" package.json > temp.json && mv temp.json package.json
        shell: bash

      - name: Build
        run: pnpm build

      - name: Setup .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to NPM
        run: pnpm publish --tag dev